server.port=8080

spring.application.name=ms-pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/db_pedidos
spring.datasource.username=postgres
spring.datasource.password=barrera120805
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# URLs de los microservicios
microservicios.inventario.url=http://localhost:8081
microservicios.pagos.url=http://localhost:8082
microservicios.notificaciones.url=http://localhost:8083

logging.level.com.saga.pedidos=DEBUG